disabled_rules:
  - identifier_name
  - trailing_whitespace
  # - block_based_kvo # swift 3.2
  # - closure_parameter_position
  # - discarded_notification_center_observer
  # - file_length
  # - function_body_length
  # - function_parameter_count
  
  # - large_tuple
  # - nesting
  # - type_body_length
  # - type_name
  # - trailing_comma
  # - weak_delegate
  # - empty_enum_arguments

line_length: 110
type_body_length:
  warning: 300
  error: 400

