language: swift
osx_image: xcode9.2

branches:
  only:
    - develop

before_install:
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
script:
  - xcodebuild -workspace Snakepit.xcworkspace -scheme Snakepit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - swiftlint

