language: objective-c
osx_image: xcode9
xcode_sdk: iphonesimulator10.0

branches:
  only:
    - develop

before_install:
  - gem install xcpretty -N

script:
- set -o pipefail
- travis_retry xcodebuild -workspace Snakepit.xcworkspace -scheme Snakepit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c


